name: Auto Update Course Data

on:
  schedule:
    # Run every 5 hours (at minute 0 of hours 0, 5, 10, 15, 20)
    - cron: '0 */5 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for git operations
        fetch-tags: true
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
    - name: Fetch all branches
      run: |
        git fetch --all
        git branch -a
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
      
    - name: Run data builder
      run: node scripts/databuilder.js --all --term=1258
      env:
        # Add any environment variables your script might need
        NODE_ENV: production
        
    - name: Switch to data branch and commit changes
      run: |
        # Switch to data branch
        git checkout -B data origin/data
        
        # Copy fresh data files from main branch (overwrite existing)
        git checkout main -- data/
        
        # Remove node_modules if it was copied
        rm -rf node_modules/
        
        # Always commit and push (we know the data is fresh)
        echo "Committing fresh data files..."
        git add data/
        git commit -m "Auto-update course data - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        git push origin data
        echo "✅ Data updated and pushed successfully"
        
        # Switch back to main
        git checkout main 